version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb+srv://deadpool:ironman@project.hlhbwnd.mongodb.net/nodeAuth2?retryWrites=true&w=majority
      JWT_SECRET: dumdum
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
